/*
 * Globalize Culture en-GB
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function(window, undefined) {

    var Globalize;

    if (typeof require !== "undefined" &&
            typeof exports !== "undefined" &&
            typeof module !== "undefined") {
        // Assume CommonJS
        Globalize = require("globalize");
    } else {
        // Global variable
        Globalize = window.Globalize;
    }

    Globalize.addCultureInfo("en", "default", {
        name: "en",
        englishName: "English",
        nativeName: "English",
        numberFormat: {
            currency: {
                pattern: ["-$n", "$n"],
                symbol: "£"
            }
        },
        calendars: {
            standard: {
                firstDay: 1,
                patterns: {
                    d: "dd/MM/yyyy",
                    D: "dd MMMM yyyy",
                    t: "HH:mm",
                    T: "HH:mm:ss",
                    f: "dd MMMM yyyy HH:mm",
                    F: "dd MMMM yyyy HH:mm:ss",
                    M: "dd MMMM",
                    Y: "MMMM yyyy"
                }
            }
        },
        messages:
                {
                    "finding_location": "Finding your location...",
                    "where_i_am": "This is where I am",
                    "location": "Location",
                    "locations": "Locations",
                    "public_wifi": "Δημόσια Wi-Fi",
                    "public_buildings": "Δημόσια κτίρια",
                    "monuments": "Αρχαία Μνημεία",
                    "beaches": "Παραλίες",
                    "restaurants": "Εστιατόρια",
                    "coffee_places": "Καφετέριες",
                    "clothes_shop": "Καταστήματα Ρούχων",
                    "public_parks": "Δημόσια Πάρκα",
                    "painting_events": "Εκδηλώσεις Ζωγραφικής",
                    "book_events": "Εκδηλώσεις Λογοτεχνίας",
                    "most_searched": "Most searched for",
                    "favourites": "Favourites",
                    "favourite_places": "Favourite Places",
                    "meter_short": "m",
                    "km_short": "km",
                    "info": "Info",
                    "pick": "Pick",
                    "about_to_request_appointment": "You are about to request an appointment.",
                    "let_them_call": "Let them call you",
                    "arrange_appointment": "Arrange Appointment",
                    "cancel": "Cancel",
                    "accepted_appointment": " has accepted the appointment request.",
                    "will_call": "He will call you",
                    "or": "or",
                    "send_details": "send appointment details soon.",
                    "confirm_appointment": "Confirm appointment",
                    "appointment": "Appointment",
                    "time_range_availability": "Time range of your availability",
                    "please_rate": "Please rate ",
                    "price": "Price",
                    "quality": "Quality",
                    "availability": "Availability",
                    "available": "Available",
                    "friend_suggestion": "Friend Suggestion",
                    "friends_suggestions": "Friends Suggestions",
                    "ongoing_cases": "Ongoing Cases",
                    "log_out": "Log Out",
                    "settings": "Settings",
                    "sort_by": "Sort By",
                    "certifications": "Certifications",
                    "offers": "Offers",
                    "discount": "discount",
                    "every_week_offers": "Every week special offers are here for you! ",
                    "email": "Email",
                    "password": "Password",
                    "login": "Login",
                    "favourite_places_link_descr": "Manage your most common places",
                    "settings_link_descr": "Manage more settings",
                    "google_places": "Google Places",
                    "public_srvs": "Public Services"
                }
    });

}(this));
