/*
 * Globalize Culture el
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function(window, undefined) {

    var Globalize;

    if (typeof require !== "undefined" &&
            typeof exports !== "undefined" &&
            typeof module !== "undefined") {
        // Assume CommonJS
        Globalize = require("globalize");
    } else {
        // Global variable
        Globalize = window.Globalize;
    }

    Globalize.addCultureInfo("el", "default", {
        name: "el",
        englishName: "Greek",
        nativeName: "Ελληνικά",
        language: "el",
        numberFormat: {
            ",": ".",
            ".": ",",
            "NaN": "μη αριθμός",
            negativeInfinity: "-Άπειρο",
            positiveInfinity: "Άπειρο",
            percent: {
                pattern: ["-n%", "n%"],
                ",": ".",
                ".": ","
            },
            currency: {
                pattern: ["-n $", "n $"],
                ",": ".",
                ".": ",",
                symbol: "€"
            }
        },
        calendars: {
            standard: {
                firstDay: 1,
                days: {
                    names: ["Κυριακή", "Δευτέρα", "Τρίτη", "Τετάρτη", "Πέμπτη", "Παρασκευή", "Σάββατο"],
                    namesAbbr: ["Κυρ", "Δευ", "Τρι", "Τετ", "Πεμ", "Παρ", "Σαβ"],
                    namesShort: ["Κυ", "Δε", "Τρ", "Τε", "Πε", "Πα", "Σά"]
                },
                months: {
                    names: ["Ιανουάριος", "Φεβρουάριος", "Μάρτιος", "Απρίλιος", "Μάιος", "Ιούνιος", "Ιούλιος", "Αύγουστος", "Σεπτέμβριος", "Οκτώβριος", "Νοέμβριος", "Δεκέμβριος", ""],
                    namesAbbr: ["Ιαν", "Φεβ", "Μαρ", "Απρ", "Μαϊ", "Ιουν", "Ιουλ", "Αυγ", "Σεπ", "Οκτ", "Νοε", "Δεκ", ""]
                },
                monthsGenitive: {
                    names: ["Ιανουαρίου", "Φεβρουαρίου", "Μαρτίου", "Απριλίου", "Μαΐου", "Ιουνίου", "Ιουλίου", "Αυγούστου", "Σεπτεμβρίου", "Οκτωβρίου", "Νοεμβρίου", "Δεκεμβρίου", ""],
                    namesAbbr: ["Ιαν", "Φεβ", "Μαρ", "Απρ", "Μαϊ", "Ιουν", "Ιουλ", "Αυγ", "Σεπ", "Οκτ", "Νοε", "Δεκ", ""]
                },
                AM: ["πμ", "πμ", "ΠΜ"],
                PM: ["μμ", "μμ", "ΜΜ"],
                eras: [{"name": "μ.Χ.", "start": null, "offset": 0}],
                patterns: {
                    d: "d/M/yyyy",
                    D: "dddd, d MMMM yyyy",
                    f: "dddd, d MMMM yyyy h:mm tt",
                    F: "dddd, d MMMM yyyy h:mm:ss tt",
                    M: "dd MMMM",
                    Y: "MMMM yyyy"
                }
            }
        },
        messages:
                {
                    "finding_location": "Finding your location...",
                    "where_i_am": "This is where I am",
                    "location": "Location",
                    "locations": "Locations",
                    "public_wifi": "Δημόσια Wi-Fi",
                    "public_buildings": "Δημόσια κτίρια",
                    "monuments": "Αρχαία Μνημεία",
                    "beaches": "Παραλίες",
                    "restaurants": "Εστιατόρια",
                    "coffee_places": "Καφετέριες",
                    "clothes_shop": "Καταστήματα Ρούχων",
                    "public_parks": "Δημόσια Πάρκα",
                    "painting_events": "Εκδηλώσεις Ζωγραφικής",
                    "book_events": "Εκδηλώσεις Λογοτεχνίας",
                    "most_searched": "Most searched for",
                    "favourites": "Favourites",
                    "favourite_places": "Favourite Places",
                    "meter_short": "m",
                    "km_short": "km",
                    "info": "Info",
                    "pick": "Pick",
                    "about_to_request_appointment": "You are about to request an appointment.",
                    "let_them_call": "Let them call you",
                    "arrange_appointment": "Arrange Appointment",
                    "cancel": "Cancel",
                    "accepted_appointment": " has accepted the appointment request.<br/><br/>He will call you<br/>or<br/>send appointment details soon.",
                    "confirm_appointment": "Confirm appointment",
                    "appointment": "Appointment",
                    "time_range_availability": "Time range of your availability",
                    "please_rate": "Please rate ",
                    "price": "Price",
                    "quality": "Quality",
                    "availability": "Availability",
                    "available": "Available",
                    "friend_suggestion": "Friend Suggestion",
                    "friends_suggestions": "Friends Suggestions",
                    "ongoing_cases": "Ongoing Cases",
                    "log_out": "Log Out",
                    "settings": "Settings",
                    "sort_by": "Sort By",
                    "certifications": "Certifications",
                    "offers": "Offers",
                    "discount": "discount",
                    "every_week_offers": "<strong>Every week</strong> special offers are here for you! ",
                    "email": "Email",
                    "password": "Κωδικός",
                    "login": "Σύνδεση",
                    "favourite_places_link_descr": "Manage your most common places",
                    "settings_link_descr": "Manage more settings",
                    "google_places": "Google Places",
                    "public_srvs": "Public Services"
                }
    });

}(this));
