/*
 * Globalize Culture el
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function(window, undefined) {

    var Globalize;

    if (typeof require !== "undefined" &&
            typeof exports !== "undefined" &&
            typeof module !== "undefined") {
        // Assume CommonJS
        Globalize = require("globalize");
    } else {
        // Global variable
        Globalize = window.Globalize;
    }

    Globalize.addCultureInfo("el", "default", {
        name: "el",
        englishName: "Greek",
        nativeName: "Ελληνικά",
        language: "el",
        numberFormat: {
            ",": ".",
            ".": ",",
            "NaN": "μη αριθμός",
            negativeInfinity: "-Άπειρο",
            positiveInfinity: "Άπειρο",
            percent: {
                pattern: ["-n%", "n%"],
                ",": ".",
                ".": ","
            },
            currency: {
                pattern: ["-n $", "n $"],
                ",": ".",
                ".": ",",
                symbol: "€"
            }
        },
        calendars: {
            standard: {
                firstDay: 1,
                days: {
                    names: ["Κυριακή", "Δευτέρα", "Τρίτη", "Τετάρτη", "Πέμπτη", "Παρασκευή", "Σάββατο"],
                    namesAbbr: ["Κυρ", "Δευ", "Τρι", "Τετ", "Πεμ", "Παρ", "Σαβ"],
                    namesShort: ["Κυ", "Δε", "Τρ", "Τε", "Πε", "Πα", "Σά"]
                },
                months: {
                    names: ["Ιανουάριος", "Φεβρουάριος", "Μάρτιος", "Απρίλιος", "Μάιος", "Ιούνιος", "Ιούλιος", "Αύγουστος", "Σεπτέμβριος", "Οκτώβριος", "Νοέμβριος", "Δεκέμβριος", ""],
                    namesAbbr: ["Ιαν", "Φεβ", "Μαρ", "Απρ", "Μαϊ", "Ιουν", "Ιουλ", "Αυγ", "Σεπ", "Οκτ", "Νοε", "Δεκ", ""]
                },
                monthsGenitive: {
                    names: ["Ιανουαρίου", "Φεβρουαρίου", "Μαρτίου", "Απριλίου", "Μαΐου", "Ιουνίου", "Ιουλίου", "Αυγούστου", "Σεπτεμβρίου", "Οκτωβρίου", "Νοεμβρίου", "Δεκεμβρίου", ""],
                    namesAbbr: ["Ιαν", "Φεβ", "Μαρ", "Απρ", "Μαϊ", "Ιουν", "Ιουλ", "Αυγ", "Σεπ", "Οκτ", "Νοε", "Δεκ", ""]
                },
                AM: ["πμ", "πμ", "ΠΜ"],
                PM: ["μμ", "μμ", "ΜΜ"],
                eras: [{"name": "μ.Χ.", "start": null, "offset": 0}],
                patterns: {
                    d: "d/M/yyyy",
                    D: "dddd, d MMMM yyyy",
                    f: "dddd, d MMMM yyyy h:mm tt",
                    F: "dddd, d MMMM yyyy h:mm:ss tt",
                    M: "dd MMMM",
                    Y: "MMMM yyyy"
                }
            }
        },
        messages:
                {
                    "finding_location": "Αναζήτηση της τοποθεσίας σας...",
                    "where_i_am": "Βρίσκομαι εδώ",
                    "location": "Τοποθεσία",
                    "locations": "Τοποθεσίες",
                    "public_wifi": "Δημόσια Wi-Fi",
                    "public_buildings": "Δημόσια κτίρια",
                    "monuments": "Αρχαία Μνημεία",
                    "beaches": "Παραλίες",
                    "restaurants": "Εστιατόρια",
                    "coffee_places": "Καφετέριες",
                    "clothes_shop": "Καταστήματα Ρούχων",
                    "public_parks": "Δημόσια Πάρκα",
                    "painting_events": "Εκδηλώσεις Ζωγραφικής",
                    "book_events": "Εκδηλώσεις Λογοτεχνίας",
                    "sign_out": "Αποσύνδεση",
                    "favourites": "Αγαπημένα",
                    "favourite_places": "Favourite Places",
                    "meter_short": "m",
                    "km_short": "km",
                    "info": "Πληροφορίες",
                    "pick": "Επιλογή",
                    "cancel": "Ακύρωση",
                    "please_rate": "Παρακαλώ αξιολογήστε ",
                    "price": "Τιμή",
                    "quality": "Ποιότητα",
                    "availability": "Διαθεσιμότητα",
                    "available": "Διαθέσιμος",
                    "log_out": "Αποσύνδεση",
                    "settings": "Ρυθμίσεις",
                    "sort_by": "Ταξινόμηση",
                    "first_name": "Όνομα",
                    "last_name": "Επώνυμο",
                    "email": "Email",
                    "password": "Κωδικός",
                    "repeat_password": 'Επανάληψη Κωδικού',
                    "passwords_no_match": 'Οι κωδικοί δεν ταιριάζουν',
                    "gender": "Φύλο",
                    "birth_date": "Ημερομηνία Γέννησης",
                    "man": "Άνδρας",
                    "woman": "Γυναίκα",
                    "login": "Σύνδεση",
                    "signup": "Εγγραφή",
                    "load_more": "Περισσότερα",
                    "submit": "Υποβολή",
                    "share_on": "Μοιράσου το σε",
                    "please_select_date": "Παρακαλώ επέλεξε ημερομηνία!",
                    "please_input_email": "Παρακαλώ εισάγετε το email σας!",
                    "please_input_first_name": "Παρακαλώ εισάγετε το όνομά σας!",
                    "please_input_last_name": "Παρακαλώ εισάγετε το επίθετό σας!",
                    "please_input_password": "Παρακαλώ εισάγετε το συνθηματικό σας!",
                    "please_select_gender": "Παρακαλώ επιλέξτε το φύλο σας!",
                    "select_date": "Επιλέξτε Ημ/νία",
                    "dateOrder": "ddMyy",
                    "dateFormat": "dd/mm/yy",
                    "parseDateFormat": "dd/MM/yyyy",
                    "cancelText": "Ακύρωση",
                    "setText": "Υποβολή",
                    "profile": "Προφίλ",
                    "edit_profile_details": "Επεξεργασία Προφίλ",
                    "edit_profile": "Αποθήκευση",
                    "details": "Λεπτομέρειες",
                    "google_places": "Google Places",
                    "public_srvs": "Δημόσιες Υπηρεσίες",
                    "existing_email": "Το email που δώσατε ανήκει σε υφιστάμενο χρήστη.",
                    "invalid_credentials": "Λάθος username ή password. Παρακαλούμε προσπαθήστε ξανά!",
                    "login_failed_msg": "Παρουσιάστηκε κάποιο σφάλμα κατά την εισοδό σας. Παρακαλούμε προσπαθήστε ξανά!",
                    "signup_failed_msg": "Παρουσιάστηκε κάποιο σφάλμα κατά την εγγραφή σας. Παρακαλούμε προσπαθήστε ξανά!",
                    "edit_profile_failed_msg": "Παρουσιάστηκε κάποιο σφάλμα κατά την επεξεργασία του προφίλ σας. Παρακαλούμε προσπαθήστε ξανά!"
                }
    });

}(this));
