/*
 * Globalize Culture en-GB
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function(window, undefined) {

    var Globalize;

    if (typeof require !== "undefined" &&
            typeof exports !== "undefined" &&
            typeof module !== "undefined") {
        // Assume CommonJS
        Globalize = require("globalize");
    } else {
        // Global variable
        Globalize = window.Globalize;
    }

    Globalize.addCultureInfo("en", "default", {
        name: "en",
        englishName: "English",
        nativeName: "English",
        numberFormat: {
            currency: {
                pattern: ["-$n", "$n"],
                symbol: "£"
            }
        },
        calendars: {
            standard: {
                firstDay: 1,
                patterns: {
                    d: "dd/MM/yyyy",
                    D: "dd MMMM yyyy",
                    t: "HH:mm",
                    T: "HH:mm:ss",
                    f: "dd MMMM yyyy HH:mm",
                    F: "dd MMMM yyyy HH:mm:ss",
                    M: "dd MMMM",
                    Y: "MMMM yyyy"
                }
            }
        },
        messages:
                {
                    "finding_location": "Finding your location...",
                    "where_i_am": "This is where I am",
                    "location": "Location",
                    "locations": "Locations",
                    "public_wifi": "Public Wi-Fi",
                    "public_buildings": "Public buildings",
                    "monuments": "Monuments",
                    "beaches": "Beaches",
                    "restaurants": "Restaurants",
                    "coffee_places": "Coffee Houses",
                    "clothes_shop": "Clothes",
                    "public_parks": "Parks",
                    "art_gallery": "Art Gallery",
                    "libraries": "Libraries",
                    "sign_out": "Sign Out",
                    "most_searched": "Most searched for",
                    "favourites": "Favourites",
                    "favourite_places": "Browse Map",
                    "meter_short": "m",
                    "km_short": "km",
                    "info": "Info",
                    "pick": "Pick",
                    "cancel": "Cancel",
                    "or": "or",
                    "please_rate": "Please rate ",
                    "price": "Price",
                    "quality": "Quality",
                    "availability": "Availability",
                    "available": "Available",
                    "friend_suggestion": "Friend Suggestion",
                    "friends_suggestions": "Friends Suggestions",
                    "ongoing_cases": "Ongoing Cases",
                    "log_out": "Log Out",
                    "settings": "Settings",
                    "sort_by": "Sort By",
                    "first_name": "First Name",
                    "last_name": "Last Name",
                    "email": "Email",
                    "password": "Password",
                    "repeat_password": 'Repeat Password',
                    "passwords_no_match": 'Passwords don\&#039;t match',
                    "gender": "Gender",
                    "birth_date": "Birth Date",
                    "man": "Man",
                    "woman": "Woman",
                    "login": "Login",
                    "signup": "Sign up",
                    "load_more": "More...",
                    "submit": "Submit",
                    "share_on": "Share on",
                    "please_select_date": "Please select a date!",
                    "please_input_email": "Please insert your email!",
                    "please_input_first_name": "Please insert your first name!",
                    "please_input_last_name": "Please insert your last name!",
                    "please_input_password": "Please insert your password!",
                    "please_select_gender": "Please select your gender!",
                    "select_date": "Select date",
                    "dateOrder": "Mddyy",
                    "dateFormat": "mm/dd/yy",
                    "parseDateFormat": "MM/dd/yyyy",
                    "cancelText": "Cancel",
                    "setText": "Set",
                    "profile": "Profile",
                    "edit_profile_details": "Edit Profile Details",
                    "edit_profile": "Save",
                    "details": "Details",
                    "favourite_places_link_descr": "Manage your most common places",
                    "settings_link_descr": "Manage more settings",
                    "google_places": "Google Places",
                    "public_srvs": "Public Services",
                    "existing_email": "The email you entered belongs to an existing user.",
                    "invalid_credentials": "Wrong username or password. Please try again!",
                    "login_failed_msg": "An error occurred during your login attempt. Please try again!",
                    "signup_failed_msg": "An error occurred during your signup. Please try again!",
                    "edit_profile_failed_msg": "An error occurred during the editing of your profile. Please try again!"
                }
    });

}(this));
